# Generated by Django 4.1.2 on 2022-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_remove_cliente_id_cliente_direccion_cliente_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fechalta',
            new_name='fecha_alta',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='mobile',
            new_name='movil',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tarifa',
            field=models.CharField(choices=[('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro'), ('DI', 'Diamante')], default='BR', max_length=2),
        ),
    ]
